### ISSUE TITLE
symfony 4 compatibility

### ISSUE THREAD

**Issue by RuSPanzer** [E-vence/SoftDeleteableListenerExtensionBundle#15]
I see that the wizard already has a support symfony 4.
But in the last stable release of it yet. When will there be a stable release with support for symfony 4?

**Comment by Trekels** [comment]
Any updates on the SF4 support ?

**Comment by RubenHarms** [comment]
I'm not aware of the major changes in SF4, as i'm not yet running SF4. If it's just a constraint, then we should add that. Feel free to contribute to a SF4 version if the changes are dramatically.

**Comment by RubenHarms** [comment]
I see that we already added the constraint in the last release. Can you both test it on SF4 and report the issues? Maybe there is somone else who already tested it?

**Comment by RuSPanzer** [comment]
i use dev-master branch in my project with SF4. all it's ok
