### ISSUE TITLE
Symfony 4.3 compatibility

### ISSUE THREAD

**Issue by arturslogins** [E-vence/SoftDeleteableListenerExtensionBundle#22]
/vendor/evence/soft-deleteable-extension -bundle/Evence/Bundle/SoftDeleteableExtensionBundle/DependencyInjection/Configuration.php:21 {
    › $treeBuilder = new TreeBuilder();
    › $rootNode = $treeBuilder->root('evence_soft_deleteable_extension');
    › 
  }

**Comment by chieftechs** [comment]
https://github.com/E-vence/SoftDeleteableListenerExtensionBundle/pull/25

**Comment by samdark** [comment]
Should this one be closed?
