### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by vincent-dravert** [E-vence/SoftDeleteableListenerExtensionBundle#24]

**Comment by jukuan** [comment]
I can confirm that it does work fine on Symfony 5. It does not work well for Symfony 6 out-of-box. But it needs only small changes to be working: https://github.com/E-vence/SoftDeleteableListenerExtensionBundle/pull/32/files

**Comment by samdark** [comment]
Should this one be closed?

**Comment by jukuan** [comment]
Yes. I think, you can close that, because the pull-request above has been merged. And there is 2024, not 2019 :)

**Comment by samdark** [comment]
I'm not repository owner.

**Comment by RubenHarms** [comment]
Closed on request!
