### ISSUE TITLE
PHP 8 attributes instead of Annotations

### ISSUE THREAD

**Issue by Slashhh-es** [E-vence/SoftDeleteableListenerExtensionBundle#34]

**Comment by RubenHarms** [comment]
Merged and release created with tag 3.2.1.

**Comment by JoolsMcFly** [comment]
@RubenHarms if I were to look into supporting attributes instead of annotations, would you be able to take time to due do a code review?

**Comment by samdark** [comment]
Should this one be closed?

**Comment by RubenHarms** [comment]
Closed on request!

**Comment by JoolsMcFly** [comment]
Hi guys. I don’t think it should be closed. It needs to support attributes as we get deprecation warnings.

I’d like to have a look at how to do this but only if you guys have time for code review.
