### ISSUE TITLE
PHP attributes are not usable

### ISSUE THREAD

**Issue by samdark** [E-vence/SoftDeleteableListenerExtensionBundle#41]
https://github.com/E-vence/SoftDeleteableListenerExtensionBundle/blob/master/Mapping/Annotation/onSoftDelete.php

```php
#[onSoftDelete(type: 'SET NULL')]
```

You can't set a public property of an attribute when using it. It should be added to constructor:

```php
final class onSoftDelete // extends Annotation
{
    // ...
    public function __coustruct($type = null)
    {
        $this->type = $type;
    }
```

**Comment by vitaly-malashevsky** [comment]
The same is being reported by phpstan <=1.10.59, btw:

> Attribute class Evence\Bundle\SoftDeleteableExtensionBundle\Mapping\Annotation\onSoftDelete does not have a constructor and must be instantiated without any parameters.
